### ISSUE TITLE
Some bugs in crud/router.go

### ISSUE THREAD

**Issue by zhqqqy** [krsoninikhil/go-rest-kit#1]
Hello, I have noticed some issues in your code. 
- Firstly, you have defined a `type HandlerFunc func(*gin.Context, any)`, where one of the parameters type is `any`. It seems that you believe this allows any type to be passed as the second argument in the function. However, in Go, function signatures must strictly match the type definition. Therefore, the function passed must also be of type `any`. If you pass a different type as the second argument, it will panic at the assertion `handler.(HandlerFunc)(c, req)`.
- The second issue is in the `bindRequest` function. You are using `ShouldBindJSON` followed by `ShouldBindQuery`, `ShouldBindUri`, and `ShouldBindHeader` methods. This can cause a problem. For example, if you have a GET request like `/?name=test&id=1&age=19` without a request body, the `ShouldBindJSON` method will return an error, and the subsequent ShouldBindQuery method will not be executed.

**Comment by krsoninikhil** [comment]
Hey @zhqqqy, thanks for going though code and noticing the problems.

The correct handler method is defined [here](https://github.com/krsoninikhil/go-rest-kit/blob/bca025a743b33df5370e05a5a3d109d0e36a9944/request/binding.go#L11-L12) which uses generic to avoid the problem you highlighted with `any` type, along with the bind methods which check for the request type being nil, so it would only parse the body if caller is expecting the body.

The `crud/router.go` file is something I was trying by defining a separate router itself rather than defining the wrapper methods for handler. This didn't work out as expected because apparently the method can use only the generic type which are defined as part of struct itself and not dynamically during method call. That's why I restructured it as wrapper methods ([here](https://github.com/krsoninikhil/go-rest-kit/blob/bca025a743b33df5370e05a5a3d109d0e36a9944/request/binding.go#L16), and [here](https://github.com/krsoninikhil/go-rest-kit/blob/c1e097cdf6d38d98db611a043ed920d52d044568/request/crud.go#L20) for crud) which takes the handler as argument and returns the gin handler. I missed to remove this file from package, it's removed now. Thanks for highlighting.
